[pytest]
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
